## Se debe parametrizar el archivo .env el cual es utilizado para paremtrizar los valore de conexion

version: "3.8"

volumes:
  mysql_data:
  glpi_data:

services:
    mysql:
        image: elestio/mysql:8.0
        restart: always
        hostname: mysql
        volumes:
            - mysql_data:/var/lib/mysql
        env_file:
            - ./.env
        ports:
            - "50778:3306"

    glpi:
        image: elestio/glpi:latest
        restart: always
        hostname: glpi
        ports:
            - "33:80"
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - glpi_data:/var/www/html/glpi
        environment:
            - TIMEZONE=Europe/Brussels
        depends_on:
            - mysql

    pma:
        image: phpmyadmin
        restart: always
        links:
            - mysql:mysql
        ports:
            - "22811:80"
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: ${ADMIN_PASSWORD}
          UPLOAD_LIMIT: 500M
          MYSQL_USERNAME: glpi
          MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
        depends_on:
            - mysql
            - glpi