version: '3.8'

services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - './postgres_data:/var/lib/postgresql/data'

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
    depends_on:
      - postgres