version: '3.8'

volumes:
  keycloak_data:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
