version: '3.9'
services:
  sonarqube:
    image: sonarqube:9.8-community
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_data:/opt/sonarqube/data
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_logs:/opt/sonarqube/logs
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      sonarqube_community_network:
        aliases:
          - sonarqube_net
volumes:
  sonarqube_data: {}
  sonarqube_logs: {}
  sonarqube_extensions: {}
networks:
  sonarqube_community_network:
    driver: bridge
    ipam:
      driver: default