version: '3.9'
services:

  postgresql:
    image: postgres:alpine3.14 # Posgresql 14.1
    restart: always
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - ~/Documentos/Docker/Volumenes/BD/postgresql:/var/lib/postgresql/data
    networks:
      sonarqube_community_network:
        aliases: 
          - postgresql_net

  sonarqube:
    image: sonarqube:9.8-community
    restart: always
    depends_on:
      - postgresql
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql_net/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: 'sonarqube'
      SONAR_JDBC_MAXACTIVE: 60
      SONAR_JDBC_MAXIDLE: 5
      SONAR_JDBC_MINIDLE: 2
      SONAR_JDBC_MAXWAIT: 5000
    volumes:
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_data:/opt/sonarqube/data
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_logs:/opt/sonarqube/logs
      - ~/Documentos/Docker/Volumenes/Sonar/sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      sonarqube_community_network:
        aliases:
          - sonarqube_net
volumes:
  sonarqube_data: {}
  sonarqube_logs: {}
  sonarqube_extensions: {}
  postgresql: {}
networks:
  sonarqube_community_network:
    driver: bridge
    ipam:
      driver: default